### ISSUE TITLE
Run pylint as GH Action

### ISSUE THREAD

**Issue by thejoeejoee** [esnvutbrno/buena-fiesta#9]
* currently, pre-commit hooks are used, but they are running without installed project dependencies
* that's not suitable for `pylint`, since `pylint-django` loads `settings.py` with all imports
* solution would be GH Action with installed deps and running `pylint` also with django module

old pre-commit hook:
```yml
- id: pylint
  name: Pylint with django plugin
  entry: poetry run pylint
  language: system
  exclude: "[a-zA-Z]*/(migrations)/(.)*"
  args: [
      "--load-plugins=pylint_django",
      "--django-settings-module=fiesta.settings",
  ]
  types: [ python ]
  require_serial: true
```
